#!/bin/bash
# Developer Testing Guide and Quick Start
# This script provides comprehensive testing and development instructions

set -e

echo "🚀 Offline Medical Assistant - Developer Testing Guide"
echo "====================================================="
echo ""

SCRIPT_DIR="$(dirname "$0")"
ROOT_DIR="$SCRIPT_DIR/.."

cd "$ROOT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo ""
    echo -e "${BLUE}$1${NC}"
    echo "$(printf '=%.0s' {1..50})"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_header "Project Overview"
echo "This is a React + Tauri desktop application that provides offline medical assistance."
echo "The app uses embedded Ollama AI for privacy-focused medical consultations."
echo ""
echo "Tech Stack:"
echo "  • Frontend: React + TypeScript + Vite + Tailwind CSS v4"
echo "  • Backend: Rust + Tauri v2"
echo "  • AI: Embedded Ollama with medical models"
echo "  • Database: SQLite via SQLx"

print_header "Quick Start - Development"
echo "1. Install dependencies:"
echo "   npm install"
echo ""
echo "2. Start development server:"
echo "   npm run tauri dev"
echo "   (This starts both frontend Vite server and Tauri backend)"
echo ""
echo "3. The app should open automatically with:"
echo "   • Frontend at http://localhost:1420"
echo "   • Tauri desktop application window"

print_header "Available Testing Scripts"
echo "Run these from the project root directory:"
echo ""
echo -e "${GREEN}Quick Health Check${NC} (30 seconds)"
echo "  npm test"
echo "  OR: bash scripts/health-check.sh"
echo "  • Verifies project structure and basic dependencies"
echo ""
echo -e "${GREEN}Frontend Tests${NC} (1-2 minutes)"
echo "  npm run test:frontend"
echo "  OR: bash scripts/test-frontend.sh"
echo "  • TypeScript compilation"
echo "  • Build verification"
echo "  • Bundle size analysis"
echo ""
echo -e "${GREEN}Backend Tests${NC} (1-2 minutes)"
echo "  npm run test:backend"
echo "  OR: bash scripts/test-backend.sh"
echo "  • Rust compilation and linting"
echo "  • Cargo build verification"
echo "  • Unit tests"
echo ""
echo -e "${GREEN}Development Server${NC} (manual testing)"
echo "  npm run test:dev"
echo "  OR: bash scripts/test-dev.sh"
echo "  • Starts full application for manual testing"
echo "  • Tests UI, navigation, and AI integration"
echo ""
echo -e "${GREEN}API Testing${NC} (manual with running app)"
echo "  npm run test:api"
echo "  OR: bash scripts/test-api.sh"
echo "  • Starts app for API endpoint testing"
echo "  • Provides manual testing checklist"
echo ""
echo -e "${YELLOW}Full Build Test${NC} (5-10 minutes, 2GB+ required)"
echo "  npm run test:build"
echo "  OR: bash scripts/test-build.sh"
echo "  • Complete Tauri application build"
echo "  • Creates platform-specific bundles"
echo "  • Large build artifacts created"
echo ""
echo -e "${BLUE}Complete Test Suite${NC} (Interactive)"
echo "  npm run test:all"
echo "  OR: bash scripts/test-all.sh"
echo "  • Runs all tests in sequence"
echo "  • Asks before running full build"

print_header "Manual Testing Checklist"
echo "When running 'npm run tauri dev', test these features:"
echo ""
echo "🏠 HomePage:"
echo "  • Welcome message and navigation"
echo "  • System status indicators"
echo "  • Quick action buttons"
echo ""
echo "💬 ChatPage:"
echo "  • Submit medical queries"
echo "  • View AI responses"
echo "  • Emergency detection"
echo "  • Response formatting"
echo ""
echo "📊 HistoryPage:"
echo "  • View past conversations"
echo "  • Search functionality"
echo "  • Export conversations"
echo ""
echo "⚙️  SettingsPage:"
echo "  • AI service start/stop"
echo "  • Model selection"
echo "  • System health check"
echo "  • Connection testing"

print_header "Troubleshooting Common Issues"
echo ""
echo "🔧 Node/NPM Issues:"
echo "  • Ensure Node.js 18+ is installed"
echo "  • Run 'npm install' to install/update dependencies"
echo "  • Clear cache: 'npm cache clean --force'"
echo ""
echo "🦀 Rust/Cargo Issues:"
echo "  • Ensure Rust 1.70+ is installed"
echo "  • Update toolchain: 'rustup update'"
echo "  • Clean build: 'cd src-tauri && cargo clean'"
echo ""
echo "🎨 Tailwind CSS Issues:"
echo "  • Using Tailwind CSS v4 (latest)"
echo "  • Check tailwind.config.js for custom colors"
echo "  • Verify @tailwindcss/postcss is installed"
echo ""
echo "🤖 AI/Ollama Issues:"
echo "  • AI service may not start automatically"
echo "  • Use Settings page to manually start AI"
echo "  • Check if Ollama is available on system"
echo "  • Embedded Ollama requires proper bundling"

print_header "Development Workflow"
echo ""
echo "👨‍💻 Day-to-day Development:"
echo "  1. Start with health check: 'npm test'"
echo "  2. Make your changes"
echo "  3. Test frontend: 'npm run test:frontend'"
echo "  4. Test backend: 'npm run test:backend' (if Rust changes)"
echo "  5. Manual test: 'npm run test:dev'"
echo ""
echo "🚀 Before Commits:"
echo "  1. Run all tests: 'npm run test:all'"
echo "  2. Verify no build errors"
echo "  3. Test key functionality manually"
echo ""
echo "📦 Release Preparation:"
echo "  1. Full test suite: 'npm run test:all'"
echo "  2. Full build test: 'npm run test:build'"
echo "  3. Test on target platforms"

print_header "File Structure Guide"
echo ""
echo "📁 Frontend (src/):"
echo "  • components/: React UI components"
echo "  • services/: API communication (api-tauri.ts)"
echo "  • context/: React context providers"
echo ""
echo "📁 Backend (src-tauri/):"
echo "  • src/lib.rs: Main Tauri commands"
echo "  • src/medical_ai.rs: AI processing logic"
echo "  • src/ollama_manager.rs: Ollama integration"
echo ""
echo "📁 Scripts (scripts/):"
echo "  • All testing and development scripts"
echo "  • health-check.sh: Quick verification"
echo "  • test-*.sh: Specific test suites"

print_header "Next Steps"
echo ""
echo "🔄 To get started immediately:"
echo "  1. Run: npm test"
echo "  2. If all checks pass, run: npm run tauri dev"
echo "  3. Test the application manually"
echo ""
echo "📚 For detailed documentation:"
echo "  • README.md: Project overview"
echo "  • OLLAMA_SETUP.md: AI integration guide"
echo "  • src-tauri/: Backend documentation"
echo ""
echo "🐛 Found issues?"
echo "  • Check scripts output for specific errors"
echo "  • Review troubleshooting section above"
echo "  • Check GitHub issues for known problems"

print_header "Script Completed"
print_success "Developer guide displayed successfully!"
echo ""
echo "Run 'bash scripts/developer-guide.sh' anytime to see this guide."
echo "Happy coding! 🎉"
